---

  - name: Install MySQL 5.7 repo
    yum: name=mysql-comm* state=latest
  - name: Start the MySQL service
    service: name=mysqld state=started enabled=true

  - name: Change mysql root password and keep track in 
    shell: |
      password_match=`awk '/A temporary password is generated for/ {a=$0} END{ print a }' /var/log/mysqld.log | awk '{print $(NF)}'`
      echo $password_match
      mysql -uroot -p$password_match --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Fadi@1234'; flush privileges; "
      echo "[client]"
      user=root
      password='Fadi@1234' > /root/.my.cnf
 
