---
# tasks file for /etc/ansible/roles/createReop
- name: install createrepo
  yum: 
    name: createrepo
    state: present

- name: install bc
  yum: 
    name: bc
    state: present

- name: disable
  shell: yum-config-manager --disable \*

- name: create repository
  shell: createrepo "/rpm"

#- name: path
 # shell: |
  #      echo '[fadi]
   #          name=Custum Repisotory
    #         baseurl=file:///rpm/
     #        enabled=1
      #       gpgcheck=0' >> /etc/yum.repos.d/fadi.repo

- name: Add repository
  yum_repository:
     name: fadi
     description: fadi repo
     baseurl: "file:///rpm/"
     enabled: yes
     gpgcheck: no

- name: enable my repo
  shell: yum-config-manager --enable fadi 