---
# tasks file for /etc/ansible/roles/connectdjango

- name: part1
  command: echo $(hostname -I)
  register: IPADDRESS
  
- name: part2
  shell: echo {{IPADDRESS.stdout}}
  register: IPADDRESStemp

#- name: Ansible copy file to remote server
 # copy:
  #  src: "/root/minUtily.txt"
   # dest: "/root/tr/"

- name: Ansible replace string 
  replace:
   path: "/root/perf/cpu/settings.py"
   regexp: 'HOSTIPADDRESS'
   replace: "{{IPADDRESStemp.stdout}}"

- name: start Django
  shell: cd "/root/perf/" && source venv/bin/activate && pip install Django==2.0.3 && pip install djangorestframework &&(( nohup python manage.py runserver "{{IPADDRESStemp.stdout}}":8000 1>/dev/null 2>&1 ) & )